### ISSUE TITLE
Add more test

### ISSUE THREAD

**Issue by TrySound** [stephenway/postcss-contrast#1]
Your code is broken. Add more tests please.
https://github.com/stephenway/postcss-contrast/blob/master/index.js#L17

**Comment by TrySound** [comment]
Oops, sorry :) Not broken. But need more tests for advanced values

**Comment by TrySound** [comment]
Also plugin name and package name should be equal

**Comment by stephenway** [comment]
Hey @TrySound, thanks for being patient with this, I've:
- Refactored the plugin
- Added more tests
- Fixed plugin name
- Released new version

**Comment by TrySound** [comment]
@stephenway I meant something like linear-gradient :)
